name: Build and Deploy API

on:
  push:
    branches: 
      - main
    paths: 
      - 'Api/**'
  workflow_dispatch:

env:
  CONFIGURATION: release
  DOTNET_VERSION: '8.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore
        run: dotnet restore Api/Api.csproj

      - name: Build
        run: dotnet build Api/Api.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test Api.Tests/Api.Tests.csproj --verbosity normal --logger trx --results-directory TestResults

      - name: Publish Api
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApi Api/Api.csproj

      - name: Upload Api
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: PublishApi

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: api
          path: api-artifact

      - name: Variable Substitution API
        uses: microsoft/variable-substitution@v1
        with:
          files: api-artifact/appsettings.json
        env:
          ConnectionStrings.TflSchoolApiContext: '${{ secrets.DATABASE_CONN_STRING }}password=${{ secrets.SQL_ADMIN_PASSWORD }}'
          ApplicationInsights.ConnectionString: ${{ secrets.APP_INSIGHTS_CONN_STRING }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.API_NAME }}
          package: api-artifact