name: Deploy Infrastructure

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: DevOps-Demo-Test
  SUBSCRIPTION_ID: 3065ef51-6e69-4ee9-a407-b2cc275f91d6

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Database
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./Infrastructure/database.bicep
        parameters: Infrastructure/database.parameters.json adminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
        failOnStdErr: false
