name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'Infrastrcuture/**'
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: DevOps-Demo-Test
  SUBSCRIPTION_ID: 3065ef51-6e69-4ee9-a407-b2cc275f91d6

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Database
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./Infrastructure/main.bicep
        deploymentMode: Incremental
        deploymentName: 'school-infra-deployment'
        parameters: Infrastructure/main.parameters.json sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }} appUserPassword=${{ secrets.APP_USER_PASSWORD }}
        failOnStdErr: false
